server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: abir12
    key-store-type: PKCS12
    key-alias: mydomain

spring:
  application:
    name: erp
  profiles:
    active: 'postgres'
