server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:mydomain.jks
    key-store-password: abir12
    key-store-type: JKS
    key-alias: mydomain

spring:
  application:
    name: erp
  profiles:
    active: 'postgres'
